- name: ensure rpm-build is installed
  yum:
    name: 'rpm-build'
    state: 'present'
  tags: ['efs-utils']

- name: build RedHat rpm
  command: 'make rpm'
  args:
    chdir: "{{ efsutils_src_dest }}"
    creates: "{{ efsutils_src_dest }}/build/amazon-efs-utils*rpm"
  tags: ['efs-utils']

- name: locate generated rpm package
  find:
    paths: "{{ efsutils_src_dest }}/build"
    patterns: "amazon-efs-utils.*\\.rpm$"
    use_regex: yes
  register: rpm_file

- name: use yum to install amazon-efs-utils package
  yum:
    name: "{{ rpm_file.files[0].path }}"
    state: present
  tags: ['efs-utils']
